url: https://soelu.github.io
baseurl: 

# Site settings
title: Sören Lubitz
email: soeren.lubitz+io@gmail.com
description: "This the comprehensive profile of Sören Lubitz. Passionate Product Owner, Agile Enthusiast, Developer and hobby photograph. Including CV, Product and Project experience and contact information."


# Team names, titles and social links
people:
- name: Sören Lubitz
  pic: 1
  position: "We are all in this together."
  social:
    - title: twitter
      url: https://twitter.com/soelu
    - title: facebook
      url: https://www.facebook.com/soelu412
    - title: stack-overflow
      url: https://stackoverflow.com/users/767422/soelu
    - title: linkedin
      url: https://www.linkedin.com/in/soeren-lubitz-8040644b/
    - title: github
      url: http://github.com/soelu
    - title: 500px
      url: https://500px.com/soelu

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/soelu
  - title: facebook
    url: https://www.facebook.com/soelu412
  - title: stack-overflow
    url: https://stackoverflow.com/users/767422/soelu
  - title: linkedin
    url: https://www.linkedin.com/in/soeren-lubitz-8040644b/
  - title: github
    url: http://github.com/soelu
  - title: 500px
    url: https://500px.com/soelu

# Postal address (add as many lines as necessary)
address:
  - line: Gompitzer Str. 43
  - line: 01157 Dresden

# Build settings
markdown: kramdown
permalink: pretty