url: https://soelu.github.io
baseurl: 

# Site settings
title: Sören Lubitz
email: soeren.lubitz+io@gmail.com
description: "This the comprehensive profile of Sören Lubitz. Passionate Product Owner, Agile Enthusiast, Developer and Amateur Photographer. Including CV, Product and Project experience and contact information."


# Team names, titles and social links
people:
- name: Sören Lubitz
  pic: 1
  position: "We are all in this together."
  # social:
  #   - title: twitter
  #     url: https://twitter.com/soelu
  #   - title: stack-overflow
  #     url: https://stackoverflow.com/users/767422/soelu
  #   - title: linkedin
  #     url: https://www.linkedin.com/in/soeren-lubitz-8040644b/
  #   - title: github
  #     url: http://github.com/soelu
  #   - title: 500px
  #     url: https://500px.com/soelu

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/soelu
    fa-icon: fa-twitter
    fa-icon-style: fab
  - title: stack-overflow
    url: https://stackoverflow.com/users/767422/soelu
    fa-icon: fa-stack-overflow
    fa-icon-style: fab
  - title: linkedin
    url: https://www.linkedin.com/in/soeren-lubitz-8040644b/
    fa-icon: fa-linkedin
    fa-icon-style: fab
  - title: github
    url: http://github.com/soelu
    fa-icon: fa-github
    fa-icon-style: fab
  - title: 500px
    url: https://500px.com/soelu
    fa-icon: fa-500px
    fa-icon-style: fab
  - title: envelope
    url: mailto:soeren.lubitz@gmail.com
    fa-icon: fa-envelope
    fa-icon-style: fas

skills:
  vals:
    - name: Trust
      details: I value and embrace trust every day and see it as one of the most important values within any relationship.
      fa-icon: fa-user-shield
      fa-icon-style: fas
    - name: Honesty
      details: Key for most interactions is honesty as it fortfies trust and partnership.
      fa-icon: fa-balance-scale
      fa-icon-style: fas
    - name: Partnership
      details: When working together in a team every success and failure is owned by the whole team and not individuals.
      fa-icon: fa-handshake
      fa-icon-style: fas
  product:
    - name: Product Ownership
      details: I cherish well made products and strive to create the best products possible. Involving the team and all stakeholders constantly and fully plays a big part for that success.
      fa-icon: fa-cube
    - name: Agile Mindset
      details: The world is changing so fast, that in order to keep up, we need to adapt. Long planning and evaluation is simply not possible most of time, not the less because information needed is not available. Try-Fail-Learn.
      fa-icon: fa-trello
      fa-icon-style: fab
    - name: Practical Thinking
      details: It is always good the take a step back and try to look at a challenge at hand from a new perspective.  Often, this leads to a practical and fitting solution.
      fa-icon: fa-check-square
      fa-icon-style: fas
  tech:
    - name: Back-end Development
      details: Java, Node.js, PHP, Ruby on Rails
      fa-icon: fa-cog
    - name: Databases
      details: MySQL, SQLite, Neo4J, InfluxDB, Oracle
      fa-icon: fa-database
    - name: RESTful API Design
      details: Swagger, SpringBoot, PHP-Symphony
      fa-icon: fa-cogs
    - name: CI/CD
      details: Jenkins, Git, Pipelines, Docker
      fa-icon: fa-code
    - name: DevOps
      details: Docker, Grafana, Kubernetes, GCP, Github, Linux, macOS, Windows
      fa-icon: fa-terminal
    - name: Front-end Development
      details: Javascript, AngularJS, React (Native), HTML5, CSS, Bootstrap
      fa-icon: fa-cog
  interest:
    - name: Photography
      details: People, Children, Nature, Architecture, Bands
      fa-icon: fa-camera-retro
    - name: Renewable Energy
      details: Keeping our planet alive is essential for us and our children.
      fa-icon: fa-globe 
    - name: Family
      details: The love and center of my life
      fa-icon: fa-heart



# Postal address (add as many lines as necessary)
address:
  - line: Gompitzer Str. 43
  - line: 01157 Dresden

# Build settings
markdown: kramdown
permalink: pretty